import HypercubeRamsey.S12.DeepDiscrepancy
import HypercubeRamsey.S12.Exceptional
import HypercubeRamsey.S12.CenteredMoment
import HypercubeRamsey.S12.InteractionTails
import HypercubeRamsey.S12.ModerateMoment
import HypercubeRamsey.S12.HomogeneousPeeling
import HypercubeRamsey.S12.RowTrimming
