import HypercubeRamsey.S06.Experiment

/-!
# Step 3 objects: descriptors and the odd-label posteriors

L6.1-Defs, part 3 (06:265–447).  A descriptor at an odd state `b` is the set of distinct (ID, type) pairs used by
its neighbouring even states (06:265–268); its data are the complete tagged tuples at those pairs.  The ID type
is generic: centre locations for actual descriptors, `Fin T` for abstract ones (06:282–283).

* Low target (06:303–366): `ξ = Z_ℓ`, `ℓ = (h_b, t_b)`, prior `π_ℓ`; candidate gate `Θ_b(ξ)`: positive prior,
  the Step 1 cap on the target prior, and the Step 2 tests of every observed type evaluated with the candidate;
  tuple references `T_{β,−ℓ}` followed by the label sampler without the hit to the name `Z_ℓ`.
* High target (06:368–447): `ξ = P_{h_b}`, prior `π⁰` (the initial law, or the candidate law given `V₀`); the
  local list `H_loc` (hidden scalars of the observed lists, the base tags of their key relations and of the
  observed types, the candidates at the bins of those keys) generated by the original local kernels with density
  `g_*` relative to uniform laws (labels) and `Λ` (tags); gate `Θ(ξ, H_loc)`: positive prior, all Step 1 tests of
  the listed hidden keys, the Step 2 tests of every observed type, every affected law recomputed at `ξ`; tuple
  references `Λ` followed by the label sampler without the hit to the name `ξ`.

`M`, `M_{−c}` are the masses of the full and `c`-deleted integrands, `L_b`, `Q_{−c}` their normalizations.  The data
tests `M > 0`, `M ≥ e^{−.02k}`, `M/M_{−c} ≥ e^{−.02k}` (matching mode and primary) are not candidate gates.
-/

namespace HypercubeRamsey
namespace S06

open OAI.HypercubeRamsey
open Classical
open scoped BigOperators

noncomputable section

namespace Ctx6

variable {γ p₀ K : ℝ} {n N : ℕ} {E : Fin N → Fin N → Prop} {G : Colour} {M : TagMix N}
variable (X : Ctx6 γ p₀ K n N E G M)
variable {Id : Type} [Fintype Id] [DecidableEq Id]

/-! ### Tuple likelihood ratios -/

/-- The likelihood ratio of one tagged tuple of type `β` at the candidate history `Hξ` relative to the reference
tag law `refTag` followed by the label sampler at `H` without the hit to the name `drop` (06:317–331, 06:400–406).
-/
def tupleRatio (Hξ H : X.Hist) (β : X.Ty) (refTag : FinProb X.ι) (drop : X.Name) (o : X.Tuple) : ℝ :=
  safeRatio6 ((X.Tβ Hξ β).w o.1) (refTag.w o.1) *
    ∏ r, safeRatio6 ((X.labelLaw Hξ (reqNames6 β) o.1).w (o.2 r))
      ((X.labelLaw H ((reqNames6 β).erase drop) o.1).w (o.2 r))

/-- The reference law of one tuple: `refTag`, then labels without the hit to `drop`. -/
def tupleRef (H : X.Hist) (β : X.Ty) (refTag : FinProb X.ι) (drop : X.Name) : FinProb X.Tuple :=
  X.tupleLawOn H ((reqNames6 β).erase drop) refTag

/-! ### Low targets (06:303–366) -/

/-- The low target key `ℓ_b`. -/
def tgt (b : X.State) : X.HKey := X.g.L.stTarget b

/-- The candidate gate `Θ_b(ξ)` (06:307–315). -/
def LowGate (H : X.Hist) (b : X.State) (D : Finset (Id × X.Ty)) (ξ : Fin N) : Prop :=
  0 < (X.hidPost H.1 (X.tgt b).1).w ξ ∧ X.Step1Cap H.1 (X.tgt b).1 ∧
    ∀ e ∈ D, X.Step2Tests (X.withHid H (X.tgt b) ξ) e.2

/-- The tuple reference of a low target: `T_{β,−ℓ}`, then labels without the hit to `Z_ℓ` (06:317–323). -/
def lowRef (H : X.Hist) (b : X.State) (β : X.Ty) : FinProb X.Tuple :=
  X.tupleRef H β (X.TβDel H β (X.tgt b)) (.hid (X.tgt b))

/-- The tagged-tuple likelihood ratio `g_e(o_e | ξ)` at a low target. -/
def lowLik (H : X.Hist) (b : X.State) (ξ : Fin N) (β : X.Ty) (o : X.Tuple) : ℝ :=
  X.tupleRatio (X.withHid H (X.tgt b) ξ) H β (X.TβDel H β (X.tgt b)) (.hid (X.tgt b)) o

/-- The low target integrand, omitting the tuple `drop` if given (06:340–343). -/
def lowWeight (H : X.Hist) (b : X.State) (D : Finset (Id × X.Ty)) (o : X.Data Id)
    (drop : Option (Id × X.Ty)) (ξ : Fin N) : ℝ :=
  (X.hidPost H.1 (X.tgt b).1).w ξ * (if X.LowGate H b D ξ then 1 else 0) *
    ∏ e ∈ D, if drop = some e then 1 else X.lowLik H b ξ e.2 (o e)

/-! ### High targets (06:368–427) -/

/-- The target name `P_{h_b}`. -/
def tgtName (b : X.State) : ParentName6 X.Bin := primaryName6 (X.g.L.stKey b)

/-- The prior `π⁰` of a named primary: the initial law, or the candidate law given `V₀` (06:370–373). -/
def priorOf (H : X.Hist) (nm : ParentName6 X.Bin) : Law N :=
  match nm with
  | .initial => X.initLaw
  | .candidate _ => X.candLaw H.1.1

/-- The hidden scalars of `H_loc`: the union of the observed lists (06:376–377). -/
def locHid (D : Finset (Id × X.Ty)) : Finset X.HKey := D.biUnion fun e => e.2.obs

/-- The base tags of `H_loc`: the key relations of the listed hidden keys and the observed types' keys
(06:377–381; the padding by observed keys is allowed by 06:383). -/
def locKeys (D : Finset (Id × X.Ty)) : Finset X.Key :=
  (X.locHid D).biUnion (fun ℓ => X.C ℓ.1) ∪ D.image fun e => e.2.key

/-- The candidates of `H_loc`: the bins of the listed keys, without the target itself. -/
def locBins (D : Finset (Id × X.Ty)) (nm : ParentName6 X.Bin) : Finset X.Bin :=
  (X.binsOf (X.locKeys D)).filter fun u => ParentName6.candidate u ≠ nm

/-- The density `g_*(H_loc | ξ)` of the local list relative to uniform laws (candidates, hidden scalars) and
`Λ` (base tags), every kernel evaluated at the candidate `ξ` (06:387–391). -/
def locDensity (H : X.Hist) (nm : ParentName6 X.Bin) (D : Finset (Id × X.Ty)) (ξ : Fin N) : ℝ :=
  let b' := X.withPar H.1 nm ξ
  (∏ u ∈ X.locBins D nm, (N : ℝ) * (X.candLaw b'.1).w (H.1.2.1 u)) *
    (∏ s ∈ X.locKeys D, safeRatio6 ((X.tagLawAt (X.parOf b') s).w (H.1.2.2 s)) (M.Λ (H.1.2.2 s))) *
      ∏ ℓ ∈ X.locHid D, (N : ℝ) * (X.hidPost b' ℓ.1).w (H.2 ℓ)

/-- The gate `Θ(ξ, H_loc)` (06:391–394). -/
def HighGate (H : X.Hist) (b : X.State) (D : Finset (Id × X.Ty)) (ξ : Fin N) : Prop :=
  0 < (X.priorOf H (X.tgtName b)).w ξ ∧
    (∀ ℓ ∈ X.locHid D, X.Step1OK (X.withParH H (X.tgtName b) ξ).1 ℓ.1) ∧
      ∀ e ∈ D, X.Step2Tests (X.withParH H (X.tgtName b) ξ) e.2

/-- The tuple reference of a high target: `Λ`, then labels without the hit to `ξ` (06:400–403). -/
def highRef (H : X.Hist) (b : X.State) (β : X.Ty) : FinProb X.Tuple :=
  X.tupleRef H β (tagLaw6 M) (.par (X.tgtName b))

/-- The tagged-tuple likelihood `g_e(o_e | ξ, H_loc)` at a high target. -/
def highLik (H : X.Hist) (b : X.State) (ξ : Fin N) (β : X.Ty) (o : X.Tuple) : ℝ :=
  X.tupleRatio (X.withParH H (X.tgtName b) ξ) H β (tagLaw6 M) (.par (X.tgtName b)) o

/-- The high target integrand `Θ g_* ∏ g_e dπ⁰`, omitting `drop` if given (06:411–417). -/
def highWeight (H : X.Hist) (b : X.State) (D : Finset (Id × X.Ty)) (o : X.Data Id)
    (drop : Option (Id × X.Ty)) (ξ : Fin N) : ℝ :=
  (X.priorOf H (X.tgtName b)).w ξ * (if X.HighGate H b D ξ then 1 else 0) *
    X.locDensity H (X.tgtName b) D ξ * ∏ e ∈ D, if drop = some e then 1 else X.highLik H b ξ e.2 (o e)

/-! ### The Step 3 posterior, masses, gates and tests at either mode -/

/-- The Step 3 integrand at the mode of `b`. -/
def s3Weight (H : X.Hist) (b : X.State) (D : Finset (Id × X.Ty)) (o : X.Data Id)
    (drop : Option (Id × X.Ty)) (ξ : Fin N) : ℝ :=
  match X.stMode b with
  | .low => X.lowWeight H b D o drop ξ
  | .high => X.highWeight H b D o drop ξ

/-- `M` (`drop = none`) and `M_{−c}` (`drop = some c`). -/
def s3Mass (H : X.Hist) (b : X.State) (D : Finset (Id × X.Ty)) (o : X.Data Id) (drop : Option (Id × X.Ty)) :
    ℝ :=
  ∑ ξ, X.s3Weight H b D o drop ξ

/-- `L_b`. -/
def s3Post (H : X.Hist) (b : X.State) (D : Finset (Id × X.Ty)) (o : X.Data Id) : Law N :=
  normalize6 (X.s3Weight H b D o none) X.y₀

/-- `Q_{−c}`: the posterior without any entry or the tag of tuple `c`. -/
def s3Del (H : X.Hist) (b : X.State) (D : Finset (Id × X.Ty)) (o : X.Data Id) (c : Id × X.Ty) : Law N :=
  normalize6 (X.s3Weight H b D o (some c)) X.y₀

/-- The true value of the target. -/
def trueTarget (H : X.Hist) (b : X.State) : Fin N :=
  match X.stMode b with
  | .low => H.2 (X.tgt b)
  | .high => (X.parOf H.1).val (X.tgtName b)

/-- The candidate gate evaluated at the true target (06:353, 06:423). -/
def S3TrueGate (H : X.Hist) (b : X.State) (D : Finset (Id × X.Ty)) : Prop :=
  match X.stMode b with
  | .low => X.LowGate H b D (X.trueTarget H b)
  | .high => X.HighGate H b D (X.trueTarget H b)

/-- The threshold `e^{−.02k}`. -/
def s3Thr : ℝ := Real.exp (-(2 / 100) * X.k)

/-- The Step 3 data tests (06:346–349, 06:422–426). -/
def S3Tests (H : X.Hist) (b : X.State) (D : Finset (Id × X.Ty)) (o : X.Data Id) : Prop :=
  0 < X.s3Mass H b D o none ∧ X.s3Thr ≤ X.s3Mass H b D o none ∧
    ∀ c ∈ D, X.Matching b c.2 → X.s3Thr * X.s3Mass H b D o (some c) ≤ X.s3Mass H b D o none

/-- A Step 3 failure: the true-target gate holds and a data test fails. -/
def S3Fail (H : X.Hist) (b : X.State) (D : Finset (Id × X.Ty)) (o : X.Data Id) : Prop :=
  X.S3TrueGate H b D ∧ ¬ X.S3Tests H b D o

/-- The reference law `Q^data` of the observed tuples (06:337–338, 06:400–406). -/
def s3RefLaw (H : X.Hist) (b : X.State) (β : X.Ty) : FinProb X.Tuple :=
  match X.stMode b with
  | .low => X.lowRef H b β
  | .high => X.highRef H b β

/-! ### Descriptors (06:265–281) -/

/-- The descriptor of an assignment `φ` of the neighbouring even states of `b` to IDs: its distinct (ID, type)
pairs (06:265–268). -/
def descOf (b : X.State) (φ : X.g.L.stNbr b → Id) : Finset (Id × X.Ty) :=
  Finset.univ.image fun a => (φ a, X.stType a.1)

/-- Admissible descriptors at `b` with IDs in a permitted set: images of assignments into `perm` using at most
`T` distinct IDs (06:274–278). -/
def descsIn (b : X.State) (perm : X.g.L.stNbr b → Finset Id) : Finset (Finset (Id × X.Ty)) :=
  ((Finset.univ : Finset (X.g.L.stNbr b → Id)).filter fun φ =>
    (∀ a, φ a ∈ perm a) ∧ (Finset.univ.image φ).card ≤ X.T).image (X.descOf b)

/-- Abstract descriptors at `b`: IDs renamed into `[T]` (06:282–283). -/
def absDescs (b : X.State) : Finset (Finset (Fin X.T × X.Ty)) :=
  X.descsIn b fun _ => Finset.univ

end Ctx6

end

end S06
end HypercubeRamsey
